### ISSUE TITLE
Importing notebook is not possible

### ISSUE THREAD

**Issue by honzov** [lambdulus/frontend#11]
**Describe the bug**
Import shows file manager to choose the notebook, but in the directory with the notebook, no file displayed.

**To Reproduce**
1. Go to Lambdulus
2. Click on Import
3. Choose dir with your notebook

**Expected behavior**

Notebook file should be visible to choose.

**Comment by honzov** [comment]
The problem here is, that the notebook has no .json extension. Don't know whether feature or bug.

**Comment by Taskkill** [comment]
Thank you for reminding me that. It was dirty-n-quick solution to asciidoc limitations for `links`.

I will fix that by creating my own file extension which will not cause the asciidoc problem and will work as formerly intended.

Once that change is deployed you should redownload the notebook from courses or simply change the file extension yourself.

**Comment by Taskkill** [comment]
Fixed in the soon to be released New Frontend by using different file extension.
