### ISSUE TITLE
Stepping through macros should be optional. 

### ISSUE THREAD

**Issue by zduka** [lambdulus/frontend#4]
I.e. 

    (+ 1 2)

should evaluate to 

    3

in single step if macro executions are turned off. This is slightly more complex as it requires the reconstruction of lambda expressions back to their macro form if done properly by stepping through the macro behind the scenes. 

A quick hack for now should be just enabling arithmetic operations on numbers in single step, where the core engine can be bypassed.

**Comment by Taskkill** [comment]
I am working on proper and really powerful way to do this. It will take just few more hours to finish it though.

**Comment by Taskkill** [comment]
Done

**Comment by Taskkill** [comment]
Implemented in [core:5671625](https://github.com/lambdulus/core/commit/567162536e3cbd216833d336b90e027d922d0e44)
