### ISSUE TITLE
Macro names should work even in single letter identifiers mode

### ISSUE THREAD

**Issue by zduka** [lambdulus/frontend#5]
I.e. in single letter identifiers enabled, when a sequence of letters is parsed, the scanner should first see if there is a macro of the same name, and if so the identifier should be treated as macro. Otherwise it should be broken down to single letter identifiers as it is now. 

Degenerate forms such as `ZEROx` (where `ZERO` is a macro and `x` is a variable) should not be allowed, i.e. a parser error.

**Comment by Taskkill** [comment]
Fixed in [core:c35f6da](https://github.com/lambdulus/core/commit/c35f6da489f7d5bed9b0299496ff119f0501799d)
